export const UPDATE_ANSWER = 'UPDATE_ANSWER';
export const UPDATE_QUESTIONS = 'UPDATE_QUESTIONS';
export const UPDATE_CATEGORY_ID = 'UPDATE_CATEGORY_ID';
export const INIT_ANSWERS = 'INIT_ANSWERS';

export const SET_SETTINGS = 'SET_SETTINGS';
export const SET_DIFFICULTY = 'SET_DIFFICULTY';
export const SET_AMOUNT = 'SET_AMOUNT';
export const SET_TOKEN = 'SET_TOKEN';